#!/bin/bash

CURL="/usr/bin/curl"
YT_DLP="yt-dlp"

SERVICE="YouTube-Audio"
ID_FIELD="id"
TITLE_FIELD="title"
YT_DLP_FORMAT="bestaudio[ext=m4a]"
TIMESTAMP_FIELD="upload_date"
TIMESTAMP_FORMAT_OPTIONS="-D %Y%m%d"
TIMESTAMP_PREFIX=""
UPLOADER_FIELD="uploader_id"

download_video () {
    local INFO_JSON=$("$YT_DLP" -j "$1" 2>/dev/null)
    # Variable is empty
    if [[ -z "${INFO_JSON}" ]]; then
        echo "error: unable to get info for '$1'" >&2
        return 1
    fi
    local ID=$(echo $INFO_JSON | jq -r ".$ID_FIELD")
    if [[ -z "${ID}" ]]; then
        echo "error: unable to get ID for '$1'" >&2
        return 1
    fi
    local TITLE=$(echo $INFO_JSON | jq -r ".$TITLE_FIELD")
    if [[ -z "${TITLE}" ]]; then
        echo "error: unable to get title for '$1'" >&2
        return 1
    fi
    local TIMESTAMP=$(echo $INFO_JSON | jq -r ".$TIMESTAMP_FIELD")
    if [[ -z "${TIMESTAMP}" ]]; then
        echo "error: unable to get timestamp for '$1'" >&2
        return 1
    fi
    local UPLOADER=$(echo $INFO_JSON | jq -r ".$UPLOADER_FIELD")
    UPLOADER=${UPLOADER##@}
    if [[ -z "${UPLOADER}" ]]; then
        echo "error: unable to get uploader for '$1'" >&2
        return 1
    fi

    if [[ ! -d "/media/$SERVICE/@$UPLOADER" ]]; then
        if ! mkdir -v -- "/media/$SERVICE/@$UPLOADER"; then
            exit 1
        fi
    fi

    cd -- "/media/$SERVICE/@$UPLOADER"

    local DIRECTORY="$ID"

    if [ ! -d "$DIRECTORY" ]; then
        if ! mkdir -v -- "$DIRECTORY"; then
            exit 1
        fi
        cd -- "$DIRECTORY"
    else
        echo "error: directory '$DIRECTORY' already exists" >&2
        return 128
    fi

    if [ ! -d "pages" ]; then
        mkdir -v -- "pages" || exit 1
        cd "pages" || exit 1
        "$YT_DLP" --newline --verbose --skip-download --write-pages "$1"
        cd "/media/$SERVICE/@$UPLOADER/$DIRECTORY" || exit 1
    fi

    "$YT_DLP" --newline --verbose --skip-download --write-description --write-info-json --write-thumbnail --convert-thumbnails png --keep-video --output "%(id)s.%(ext)s" "$1"

    "$YT_DLP" --newline --verbose --format "$YT_DLP_FORMAT" --keep-video --output "%(id)s.%(ext)s" "$1"

    if [[ "$PWD" = "/media/$SERVICE/@$UPLOADER/$DIRECTORY" ]]; then
        touch -t "$(date $TIMESTAMP_FORMAT_OPTIONS -d "$TIMESTAMP_PREFIX$TIMESTAMP" +%Y%m%d%H%M.%S)" -- ./"$ID"*
        touch -t "$(date $TIMESTAMP_FORMAT_OPTIONS -d "$TIMESTAMP_PREFIX$TIMESTAMP" +%Y%m%d%H%M.%S)" .
    fi

    return 0
}

for url in "$@"; do
    download_video "$url"
done
